server:
  port: 6020

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver